apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.13.3
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller
        commandArgs:
          - --update-status
          - --log-level=info
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        podSecurityContext:
          enabled: true
          fsGroup: 65534
        serviceMonitor:
          enabled: false
        dashboards:
          enabled: false
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 1m0s
        factor: 2