apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: gitops-example
  source:
    helm:
      valueFiles:
        - values.yaml
    path: apps
    repoURL: git@github.com:biskitsx/watcher-infra.git
    targetRevision: HEAD
  syncPolicy: {}
