---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrar
namespace: dev
images:
  - name: blank
    newName: ksuphaky/watcher
    newTag: 1b47da1ff5c18cc17ab97ddf173c672c12e8181e
  - name: model-img
    newName: sstepz/watcher-rec
    newTag: v5

resources:
  - ./sealed-secret.yaml
  # - ./sealed-secret-model.yaml
  - ./namespace.yaml
  - ../../base
