---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrar
namespace: dev
images:
  - name: blank
    newName: ksuphaky/watcher
    newTag: main # will update by build agent

resources:
  - ./namespace.yaml
  - ../../base
  - ./sealed-secret.yaml
