---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrar
namespace: dev
images:
  - name: blank
    newName: ksuphaky/watcher
    newTag: 3c2bfffd9cd849b1cfbacc8d519ee7a932a94ac1
  - name: model-img
    newName: sstepz/watcher-rec
    newTag: v5

resources:
  - ./sealed-secret.yaml
  # - ./sealed-secret-model.yaml
  - ./namespace.yaml
  - ../../base
