---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: model
  namespace: dev
spec:
  encryptedData:
    MONGO_PASSWORD: AgBlLonHyNkYvgENW2KPkrKu74DgAu0YbeSFpEfLXveYRxHbYIItds4YO2Hj/jD7D7B/JzWj/4+jQBPTlCpll+PDHSm5Yxsr9ATjd9OLBw7bqlpOUiR1usnA8vsly6ytZJyfrxIjKoDxPa7Gw9D+mJHX3Rq0ktKMYFhW6dnyNVXscd20aN8dVmWr4YhY6kttsWmZb8rsZMNtrrQ1IzeGiyvSJOfDbw2cgzKKUEoa9VFegX9NKvfQtDmi+AncZ6bNxzdHtZNJekJA3qyyfE8qxPc8qxcUgzoFnCSHirGd3A0epGRJrm/gGg4OzULhlypBS3R9/uCVVk48JKBZahIMrFajITVTAD25QkJTbCXMR/F7z1gUP33wEZzkD859J0A/YAhxT/y7PxQEgV9QkXxuvI/gvPe5t1PUnqWBagn4GWKGAARTd/jxFv7eHZvRTUfeUxr847RpkhP2FytjiJ0zs4NI7JAG5VpkaLNEPGFAFD9//fG5JBD7b+kKjqC2HsJFY/8EuwRUvVI4QELwVSs98hF1rD+1YCkRQkUDRKvrs5R/O4ryKotFosC6ZU81+jlERcL+D/lOMcKigguSvDSQ6p5QFKwQvZziU1x52MmDkXisW2jWBePMCDzu4rU4tjWUI9J7kg3fwg2aQX7cSXnTKJhHevpkpOyshbCKi/1D198WCRE/NPfpJZ1qY+02Roikk52RHPVP1dFCSrQaqLwOm5Si
    MONGO_USERNAME: AgAUApUuE8C477ORcV3J2J5lr6+z27YFnHeekNEgf2WbUzojkHbqsnFlqY5KIaX0aU8Qaddqf35Bz63Cp+AG+hvEpSS40ZoirphVM31B0KjQP1wqJ29Uo6aveBwEM3UN4eY5xpoEl/HxcdW7mtgG+vrs5HaOysofbOk2cVjvdkiyeyt5kgr7QZO0/WIJIgrhhbzrgVx15z+r10m+Nbbtxh71G8Fy6BtgAS6czHeeLvL+twADNXrrdLWmhtU/GCjqUyAvAgKmmnZ2q29G3e274gy/uAdjoNcnPuocWfYpbC9oc3XKUHH/Cws5t/F4Sh6Nv9E9JlahjW4lH30s1AivJFwLn5L0QoIp6Xp6CBwSlz67dd5BzeojJP78BZxkAYt9rWshwvGVoBOh2xWu4GJ+9OwrqLMt9UEAP1tc2qhijX/OTeOEiwNVIklBOj9gD2r2M9e970IPlXdoA+KLjOpHyRmzbyfHGdbL0lkR3GSkaXTVjhkAFB1lRhPzowD6LYS/LUxOvFJHf9Z6bc+y7HwNqfvS13wGR1Y3u/j4INzo9cXD7o55Jrv6fDeyP8J7fkgpSI2kUEZBKDos5a4g0bUnfYHkAnPxtI0Bj5WSjxenlXZmfLw+zGUMK3seaVJh9rXJAxoBJ/diCPHvO253cfVSzZFJDOZ/sHEx9Kb82sZ82w3GYK6eOcNh9P6Z0fO0NG7Lili2QVteq7tcnEI=
  template:
    metadata:
      creationTimestamp: null
      name: model
      namespace: dev
