apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watcher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/biskitsx/watcher-infra.git
    path: gitops/apps/watcher/overlay/dev  # Path to your overlay
    targetRevision: HEAD
    # kustomize:
      # version: v5.0.1  # Specify kustomize version
      # Add any kustomize-specific settings if needed
      # images:
      #   - name: watcher
      #     newTag: v1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 1m0s
        factor: 2