apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: watcher 
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: watcher.suphakit.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: watcher
            port:
              number: 80
