---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: app

# namePrefix:
#   watcher-

resources: 
- ./deployment.yaml
- ./config.yaml
- ./service.yaml



# commonAnnotations:
#   app: mykustom-annontations



# nameSuffix:
#   -v1
